replicaCount: 1
namespace: algorithms-catalogue

image:
  repository: swr.eu-nl.otc.t-systems.com/vito/apex-algorithms-catalogue-web
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: default-secret

service:
  type: ClusterIP
  port: 4321

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  name: algorithms-catalogue
  hosts:
    - host: algorithms-catalogue.apex.esa.int
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: algorithms-catalogue-tls
      hosts:
        - algorithms-catalogue.apex.esa.int

resources:
  requests:
    memory: "128Mi"
    cpu: "250m"
  limits:
    memory: "256Mi"
    cpu: "500m"

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  # minReplicas: 1
  # maxReplicas: 100
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

serviceAccount:
  create: false
