apiVersion: v1
kind: Service
metadata:
  name: {{ include "algorithms-catalogue-web.fullname" . }}
  labels:
    {{- include "algorithms-catalogue-web.labels" . | nindent 4 }}
  {{- with .Values.namespace }}
  namespace: {{ . }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "algorithms-catalogue-web.selectorLabels" . | nindent 4 }}
